get:
  tags:
  - System
  summary: Get config
  description: |
    Gets config record

    **Auth:** Requires valid admin token with one of the following permissions:
    - `get_configs_identity`
    - `update_configs_identity`
    - `delete_configs_identity`
    - `all_configs_identity`
  security:
    - bearerAuth: []
  parameters:
  - name: id
    in: path
    description: ID of config to retrieve
    required: true
    style: simple
    explode: false
    schema:
      type: string
  responses:
    200:
      description: Success
      content:
        application/json:
          schema:
            $ref: "../../schemas/application/Config.yaml"
    400:
      description: Bad request
    401:
      description: Unauthorized
    500:
      description: Internal error
put:
  tags:
  - System
  summary: Save config
  description: |
    Saves config record

    **Auth:** Requires valid admin token with `update_configs_identity` or `all_configs_identity`  permission
  security:
    - bearerAuth: []
  parameters:
  - name: id
    in: path
    description: ID of config to update
    required: true
    style: simple
    explode: false
    schema:
      type: string
  requestBody:
    description: New config content
    content:
      application/json:
        schema:
          $ref: "../../schemas/application/Config.yaml"
  responses:
    200:
      description: Success
      content:
        text/plain:
          schema:
            type: string
            example: Success
    400:
      description: Bad request
    401:
      description: Unauthorized
    500:
      description: Internal error
delete:
  tags:
  - System
  summary: Delete config
  description: |
    Deletes config record

    **Auth:** Requires valid admin token with `delete_configs_identity` or `all_configs_identity` permission
  security:
    - bearerAuth: []
  parameters:
  - name: id
    in: path
    description: ID of config to delete
    required: true
    style: simple
    explode: false
    schema:
      type: string
  responses:
    200:
      description: Success
      content:
        text/plain:
          schema:
            type: string
            example: Success
    400:
      description: Bad request
    401:
      description: Unauthorized
    500:
      description: Internal error