// GENERATED BY THE COMMAND ABOVE; DO NOT EDIT
// This file was generated by swaggo/swag

package docs

import (
	"bytes"
	"encoding/json"
	"strings"

	"github.com/alecthomas/template"
	"github.com/swaggo/swag"
)

var doc = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{.Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "license": {
            "name": "Apache 2.0",
            "url": "http://www.apache.org/licenses/LICENSE-2.0.html"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/laundry/initrequest": {
            "get": {
                "security": [
                    {
                        "RokwireAuth UserAuth": []
                    }
                ],
                "consumes": [
                    "application/json"
                ],
                "tags": [
                    "Client"
                ],
                "summary": "Returns the problem codes and pending service reqeust status for a laundry machine.",
                "operationId": "InitRequest",
                "parameters": [
                    {
                        "type": "string",
                        "description": "machine service tag id",
                        "name": "machineid",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/model.MachineRequestDetail"
                        }
                    }
                }
            }
        },
        "/laundry/requestservice": {
            "get": {
                "security": [
                    {
                        "RokwireAuth UserAuth": []
                    }
                ],
                "consumes": [
                    "application/json"
                ],
                "tags": [
                    "Client"
                ],
                "operationId": "RequestService",
                "parameters": [
                    {
                        "description": "body json",
                        "name": "data",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/model.ServiceSubmission"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/model.ServiceRequestResult"
                        }
                    }
                }
            }
        },
        "/laundry/roomdetail": {
            "get": {
                "security": [
                    {
                        "RokwireAuth UserAuth": []
                    }
                ],
                "consumes": [
                    "application/json"
                ],
                "tags": [
                    "Client"
                ],
                "summary": "Returns the list of machines and the number of washers and dryers available in a laundry room",
                "operationId": "Room",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Room id",
                        "name": "id",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/model.RoomDetail"
                        }
                    }
                }
            }
        },
        "/laundry/rooms": {
            "get": {
                "security": [
                    {
                        "RokwireAuth": []
                    }
                ],
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Client"
                ],
                "summary": "Get list of all campus laundry rooms",
                "operationId": "Rooms",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/model.Organization"
                        }
                    }
                }
            }
        },
        "/token": {
            "post": {
                "security": [
                    {
                        "RokwireAuth UserAuth": []
                    }
                ],
                "consumes": [
                    "application/json"
                ],
                "tags": [
                    "Client"
                ],
                "operationId": "Name",
                "parameters": [
                    {
                        "description": "body json",
                        "name": "data",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/sampleRecord"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": ""
                    }
                }
            }
        },
        "/version": {
            "get": {
                "security": [
                    {
                        "RokwireAuth": []
                    }
                ],
                "description": "Gives the service version.",
                "produces": [
                    "text/plain"
                ],
                "tags": [
                    "Client"
                ],
                "operationId": "Version",
                "responses": {
                    "200": {
                        "description": ""
                    }
                }
            }
        }
    },
    "definitions": {
        "model.Appliance": {
            "type": "object",
            "properties": {
                "applianceType": {
                    "type": "string"
                },
                "averageCycleTime": {
                    "type": "integer"
                },
                "id": {
                    "type": "string"
                },
                "outofService": {
                    "type": "boolean"
                },
                "status": {
                    "type": "string"
                },
                "timeRemaining": {
                    "type": "string"
                }
            }
        },
        "model.LaundryRoom": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "integer"
                },
                "name": {
                    "type": "string"
                },
                "status": {
                    "type": "string"
                }
            }
        },
        "model.MachineRequestDetail": {
            "type": "object",
            "properties": {
                "machineID": {
                    "type": "string"
                },
                "message": {
                    "type": "string"
                },
                "openIssue": {
                    "type": "boolean"
                },
                "problemCodes": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                }
            }
        },
        "model.Organization": {
            "type": "object",
            "properties": {
                "laundryRooms": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/model.LaundryRoom"
                    }
                },
                "schoolName": {
                    "type": "string"
                }
            }
        },
        "model.RoomDetail": {
            "type": "object",
            "properties": {
                "appliances": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/model.Appliance"
                    }
                },
                "campusName": {
                    "type": "string"
                },
                "numDryers": {
                    "type": "integer"
                },
                "numWashers": {
                    "type": "integer"
                },
                "roomName": {
                    "type": "string"
                }
            }
        },
        "model.ServiceRequestResult": {
            "type": "object",
            "properties": {
                "message": {
                    "type": "string"
                },
                "requestNumber": {
                    "type": "integer"
                },
                "status": {
                    "type": "string"
                }
            }
        },
        "model.ServiceSubmission": {
            "type": "object",
            "properties": {
                "comments": {
                    "type": "string"
                },
                "firstname": {
                    "type": "string"
                },
                "lastname": {
                    "type": "string"
                },
                "machineid": {
                    "type": "string"
                },
                "phone": {
                    "type": "string"
                },
                "problemtype": {
                    "type": "string"
                }
            }
        },
        "sampleRecord": {
            "type": "object",
            "properties": {
                "name": {
                    "type": "string"
                }
            }
        }
    },
    "securityDefinitions": {
        "AdminUserAuth": {
            "type": "apiKey",
            "name": "Authorization",
            "in": "header (add admin id token with Bearer prefix to the Authorization value)"
        },
        "InternalAuth": {
            "type": "apiKey",
            "name": "INTERNAL-API-KEY",
            "in": "header"
        },
        "RokwireAuth": {
            "type": "apiKey",
            "name": "ROKWIRE-API-KEY",
            "in": "header"
        },
        "UserAuth": {
            "type": "apiKey",
            "name": "Authorization",
            "in": "header (add client id token with Bearer prefix to the Authorization value)"
        }
    }
}`

type swaggerInfo struct {
	Version     string
	Host        string
	BasePath    string
	Schemes     []string
	Title       string
	Description string
}

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = swaggerInfo{
	Version:     "0.1.0",
	Host:        "localhost",
	BasePath:    "/gateway/api",
	Schemes:     []string{"https"},
	Title:       "Rokwire Gatewauy Building Block API",
	Description: "Rokwire Rokwire Building Block API Documentation.",
}

type s struct{}

func (s *s) ReadDoc() string {
	sInfo := SwaggerInfo
	sInfo.Description = strings.Replace(sInfo.Description, "\n", "\\n", -1)

	t, err := template.New("swagger_info").Funcs(template.FuncMap{
		"marshal": func(v interface{}) string {
			a, _ := json.Marshal(v)
			return string(a)
		},
	}).Parse(doc)
	if err != nil {
		return doc
	}

	var tpl bytes.Buffer
	if err := t.Execute(&tpl, sInfo); err != nil {
		return doc
	}

	return tpl.String()
}

func init() {
	swag.Register(swag.Name, &s{})
}
