openapi: 3.0.3
info:
  title: Rokwire Gateway Building Block API
  description: Gateway Building Block API Documentation
  version: 2.17.0
servers:
  - url: 'https://api.rokwire.illinois.edu/gateway'
    description: Production server
  - url: 'https://api-test.rokwire.illinois.edu/gateway'
    description: Test server
  - url: 'https://api-dev.rokwire.illinois.edu/gateway'
    description: Development server
  - url: 'http://localhost/gateway'
    description: Local server
tags:
  - name: Client
    description: Client applications APIs.
  - name: Admin
    description: Clients administration applications APIs.
  - name: BBs
    description: Building Block APIs.
  - name: TPS
    description: Third-Party Service APIs.
  - name: System
    description: Third-Party Service APIs.
  - name: Default
    description: Default APIs.
paths:  
  # Default
  /version:
    $ref: "./resources/default/version.yaml"

  # Client
  /api/examples/{id}:
    $ref: "./resources/client/examples-id.yaml"
  /api/wayfinidng/buildng:
    $ref: "./resources/client/building.yaml"
  /api/wayfinding/buildings:
    $ref: "./resources/client/buildings.yaml"
  /api/wayfinding/floorplan:
    $ref: "./resources/client/floorplan.yaml"
  /api/wayfinding/searchbuildings:
    $ref: "./resources/client/searchbuildings.yaml"
  /api/termsessions/listcurrent:
    $ref: "./resources/client/termsessions.yaml"
  /api/laundry/rooms:
    $ref: "./resources/client/laundryrooms.yaml"
  /api/laundry/room:
    $ref: "./resources/client/laundryroomdetail.yaml"
  /api/laundry/initrequest:
    $ref: "./resources/client/laundryinitrequest.yaml"
  /api/laundry/requestservice:
    $ref: "./resources/client/laundryrequestservice.yaml"
  /api/person/contactinfo:
    $ref: "./resources/client/contactinfo.yaml"
  /api/person/giescourses:
    $ref: "./resources/client/giescourses.yaml"
  /api/person/studentcourses:
    $ref: "./resources/client/studentcourses.yaml"
  
  # Admin
  /api/admin/examples:
    $ref: "./resources/admin/examples.yaml"
  /api/admin/examples/{id}:
    $ref: "./resources/admin/examples-id.yaml"
  /api/admin/configs:
    $ref: "./resources/admin/configs.yaml"
  /api/admin/configs/{id}:
    $ref: "./resources/admin/configs-id.yaml"
  /api/admin/webtools-blacklist:
    $ref: "./resources/admin/webtools-blacklist.yaml"
  /api/admin/events/webtools-blacklist:
    $ref: "./resources/admin/events_webtools-blacklist.yaml"    
  /api/admin/events/summary:
    $ref: "./resources/admin/events_summary.yaml"    
  /api/admin/events/load:
    $ref: "./resources/admin/events_load.yaml"     

  # BBs
  /api/bbs/examples/{id}:
    $ref: "./resources/bbs/examples-id.yaml"
  /api/bbs/appointments/units:
    $ref: "./resources/bbs/apptunits.yaml"
  /api/bbs/appointments/people:
    $ref: "./resources/bbs/apptpeople.yaml"
  /api/bbs/appointments/slots:
    $ref: "./resources/bbs/apptslots.yaml"
  /api/bbs/appointments/questions:
    $ref: "./resources/bbs/apptquestions.yaml"
  /api/bbs/appointments/qands:
    $ref: "./resources/bbs/apptqands.yaml"
  /api/bbs/appointments/:
    $ref: "./resources/bbs/createappointment.yaml"
  /api/bbs/appointments/{id}:
    $ref: "./resources/bbs/delappointment.yaml"
  /api/bbs/events:
    $ref: "./resources/bbs/legacyEvents.yaml"  
  
  # TPS
  /api/tps/examples/{id}:
    $ref: "./resources/tps/examples-id.yaml"
  /api/tps/events:
    $ref: "./resources/tps/legacy-events.yaml"  

  # System
  /api/system/examples/{id}:
    $ref: "./resources/system/examples-id.yaml"
    
components:
  securitySchemes:
      bearerAuth:
        type: http
        scheme: bearer
        bearerFormat: JWT
  schemas:
    $ref: "./schemas/index.yaml"